### ISSUE TITLE
Istvanpince provider includes unwanted parts in the items array

### ISSUE THREAD

**Issue by ocReaper** [wolfika/daily-menu#2]
Sometimes they have a special offer marked with `NAPI AJÁNLAT:` along with the `Mai menü :` which breaks the output. If they have a special offer the `getMenu` only returns the part with `NAPI AJÁNLAT:`

**Comment by wolfika** [comment]
Hi @ocReaper! A partial fix by @peppertom just got merged, however, it does not fix the problem 100%. The scraper currently includes the string `NAPI AJÁNLAT : ` in the `dailyMenu` array, which is treated as the `items` array in the main script. It's semantically incorrect to have this string amongst the menu items. In the CLI it looks fine, but facilitating this package in form of e.g. an API, it may create some weird results.

I'm leaving this issue open, PRs are more than welcome.
Thanks!
