### ISSUE TITLE
Rethinking the idea of the output

### ISSUE THREAD

**Issue by wolfika** [wolfika/daily-menu#20]
Several problems have arisen with the way the individual menu items are extracted from the scraped HTMLs, one major reason being that the markup and the text is not always structured exactly the same way. Ideally, I wanted the output only to contain the individual menu items coming from the `items` array, but for the afromentioned reason, this, in some cases, is nearly impossible.

I'd say we go the easy way and drop that restriction, and display the entire scraped text, without even attempting to extract actual food items from the markup. This would of course in some way reduce the usability of the module as an API, as it would contain words which are not closely related to the menu served, but would highly contribute to the usability of the CLI, which in this project is more important.

What do you guys think? @ocReaper @peppertom

**Comment by peppertom** [comment]
@wolfika I agree with You. Considering the usability of the CLI, it is definitely a clear step to drop the functionalities related to the formatting/structuring of scraped data. Furthermore I suggest to move these formatters (word excluders?) to a separate module that is ought to be reusable for different raw data entities coming from various sources (e.g. websites, social media, etc.).

**Comment by wolfika** [comment]
Will be resolved in 1.0.0.
