### ISSUE TITLE
Add Bellagio Ristorante & Lounge Bar to restaurants

### ISSUE THREAD

**Issue by bolint** [wolfika/daily-menu#7]
Bellagio Ristorante & Lounge Bar
7621 Pécs, Király u.19.
E-mail: bellagio@bellagioristorante.hu
Web: www.bellagioristorante.hu

**Comment by ocReaper** [comment]
Hi @bolint!
This restaurant is currently closed, so I think it's not relevant for the current state of the app.

**Comment by bolint** [comment]
Oh, thank you!
